### ISSUE TITLE
Feature: Allow Editors to Purge All

### ISSUE THREAD

**Issue by DeathStapler** [its-cloudflare/umich-cloudflare#6]
Editors can Purge a Page or a Section but cannot Purge All.  Could you add a toggle on the options page granting editors the ability to Purge All?

There are a couple situations that we have seen.

* Uploading PDF and DOC files outside of WordPress.  We have some files that are uploaded to the server outside of WP.
* Using a plugin (Enable Media Replace) to update an existing Media item.  The plugin doesn't appear to catch the change, so the old version still gets served through Cloudflare.

Giving Editors the ability to Purge All would give them the ability to resolve the issue without having to contact us for help.

**Comment by nobleclem** [comment]
I have updated the plugin to allow editors to purge all cache in version 1.0.9.

The other issue is a little more complex however the existing integration with EMR is still working.  Cloudflare should be getting the purge request for any media files and their resized versions when a file is replaced.

The problem I think you are actually experiencing in this case is that the browser is actually not requesting the updated version from cloudflare rather than just serving the locally cached version on disk.  This is due to how static content cache lifetime is declared.  I am a little hesitant on changing this as any change would have performance consequences.  In addition if the site is hosted on Pantheon then I don't think that is a value we can change.

I am going to leave this open for now while I do some more research and have some discussions with the U-M ITS Cloudflare team.

**Comment by nobleclem** [comment]
I talked it over with ITS and we have made some adjustments to the static file asset defaults.  The default max time it will cache in the browser is 1 hour and then 1 year in cloudflare.  If you are hosting your site where .htaccess is used this change will happen when you update to version 1.0.10.

If you are hosting on Pantheon this update will not work.  Due to how Pantheon's hosting environment is currently configured we cannot update the static file cache-control headers on the hosting side.  If the site is behind cloudflare we have a workaround that is working and can be enabled for your site.  You can contact the U-M ITS Cloudflare support team.

Let us know if there is anything else.
